steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/quantum-tracker-410709/continuously-service:latest', '.', '-f', 'MLOps_MnistProject/app/simple_fastapi_app.dockerfile']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/quantum-tracker-410709/continuously-service:latest']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'continuously-service'
  - '--image'
  - 'gcr.io/quantum-tracker-410709/continuously-service:latest'
  - '--region'
  - 'europe-west1'
